### ISSUE TITLE
ArrayOutOfBounds when rotating blocks with CoFH-TE

### ISSUE THREAD

**Issue by e3r** [fewizz/NotEnoughIDs#13]
If you try to rotate a block with the CoFH-TE wrench that has an ID higher than 4095, it'll go out of bounds due to the way CoFH has implemented its BlockHelper. 

See line 33 here: https://github.com/CoFH/CoFHLib/blob/master/src/main/java/cofh/lib/util/helpers/BlockHelper.java

Which gets accessed by cofh.lib.util.helpers.BlockHelper.canRotate(BlockHelper.java:382) as per the stacktrace:

java.lang.ArrayIndexOutOfBoundsException: 11338
	at cofh.lib.util.helpers.BlockHelper.canRotate(BlockHelper.java:382)
	at cofh.thermalexpansion.item.tool.ItemWrench.onItemUseFirst(ItemWrench.java:66)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(PlayerControllerMP.java:317)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

**Comment by fewizz** [comment]
will be fixed.

**Comment by fewizz** [comment]
now? https://drive.google.com/open?id=0B0GYhmakgvItMnJrZnVTbHZDMU0 ,  https://drive.google.com/open?id=0B0GYhmakgvItazcxZUVHLV9kMVk

**Comment by Solarstrike** [comment]
@fewizz Does this also fix #14?

**Comment by fewizz** [comment]
no :disappointed:

**Comment by e3r** [comment]
I haven't had much time to test it in depth, but rotating things with the TE wrench seems to not crash now for blocks with ID higher than the old limit. :)

**Comment by fewizz** [comment]
yay.
