### ISSUE TITLE
Incompatibility with Chisels & Bits

### ISSUE THREAD

**Issue by APolarBaer** [fewizz/NotEnoughIDs#48]
Causes certain other mod blocks to go invisible when chiseled in C&B V12.3-12.7
as seen here in this thread:
https://github.com/AlgorithmX2/Chisels-and-Bits/issues/181

**Comment by whatthedrunk** [comment]
This is still happening with at least one of my users worlds. If you load [this world](https://drive.google.com/open?id=0Bybf4mi0zU-uQl8yM2dQQmZ4T0k) with All the mods version 1.5.7 and go to x982 y100 z-301 everything is fine. Then add your mod and load it again and it breaks all the the chisels and bits stuff. [Imgur Album](https://imgur.com/a/ruPyy)

**Comment by fewizz** [comment]
@whatthedrunk , i need your "mods" and "config" folders

**Comment by Magi1053** [comment]
This is still an issue
```
[Server thread/ERROR] [chiselsandbits]: Unable to read blob.
java.io.EOFException: Unexpected end of ZLIB input stream
        at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240) ~[?:1.8.0_144]
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158) ~[?:1.8.0_144]
        at mod.chiselsandbits.chiseledblock.data.VoxelBlob.read(VoxelBlob.java:926) ~[VoxelBlob.class:?]
        at mod.chiselsandbits.chiseledblock.data.VoxelBlob.blobFromBytes(VoxelBlob.java:911) ~[VoxelBlob.class:?]
        at mod.chiselsandbits.chiseledblock.data.VoxelBlobStateInstance.getBlobCatchable(VoxelBlobStateInstance.java:105) ~[VoxelBlobStateInstance.class:?]
        at mod.chiselsandbits.chiseledblock.data.VoxelBlobStateInstance.getBlob(VoxelBlobStateInstance.java:89) [VoxelBlobStateInstance.class:?]
        at mod.chiselsandbits.chiseledblock.data.VoxelBlobStateReference.getVoxelBlob(VoxelBlobStateReference.java:105) [VoxelBlobStateReference.class:?]
        at mod.chiselsandbits.chiseledblock.NBTBlobConverter.readChisleData(NBTBlobConverter.java:209) [NBTBlobConverter.class:?]
        at mod.chiselsandbits.chiseledblock.TileEntityBlockChiseled.readChisleData(TileEntityBlockChiseled.java:358) [TileEntityBlockChiseled.class:?]
        at mod.chiselsandbits.chiseledblock.TileEntityBlockChiseled.func_145839_a(TileEntityBlockChiseled.java:390) [TileEntityBlockChiseled.class:?]
        at net.minecraft.tileentity.TileEntity.func_190200_a(TileEntity.java:123) [aqk.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:486) [atj.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:96) [ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150) [ChunkIOExecutor.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:673) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by Dpuzak** [comment]
Has there been any updates with this one? I'm shaving a simillar issue as Magi1053. The game crashes once I install the mod and it's a simillar loooking error coming from chisel and bits.

Thats on the 1.10 minecraft version.

I can share my mods and config if it helps.

**Comment by HeberonYT** [comment]
get the same error in 1.12.2, I can't believe this is still open from 2016
Chisel-MC1.12.2-1.0.2.45.jar
chiselsandbits-14.33.jar
NotEnoughIDs-1.5.4.4.jar

https://pastebin.com/raw/rAheDi1F
