### ISSUE TITLE
question: are there known incompatibilities to advanced rocketry ?

### ISSUE THREAD

**Issue by DietmarKrause** [fewizz/NotEnoughIDs#55]
I am playing a modpack "all the mods" 1.10.2 which has included just enough ids some time ago. In a recent update they included advanced rocketry and other stuff, since then old worlds are not compatible any more, they simply dont show up in the single player menue or, if they do so, are corrupt with ID mismatch. There is the issue : https://github.com/whatthedrunk/allthemods/issues/447 . 
My question now is: are there known issues with advanced rocketry or other mods one should know with just enough ids? ? Any ideas if this is correlated to just enough ids?

**Comment by sfPlayer1** [comment]
Please upload the following files for further investigation:
- saves/[save-name]/level.dat from before and after the migration
- logs/latest.txt and logs/fml-client-latest.txt right after migration (1st launch+attempt to load any previously intact 2.4 world)

Whether a save game is listed in the single player world selection menu depends on the presence of an intact level.dat file. The same file also store the ID map.

**Comment by DietmarKrause** [comment]
thank you. I will provide you with these files in the next days, though there was no starting of the world after the migrstion and i fear the level.dat files should be the same. (i downgrades to 2.4 and the world could be loaded and was played since then) as stated in the original issue in ATM linked in the message.

**Comment by PotDucky** [comment]
Hey sfPlayer1, Current maintainer of ATM1 here, I've been trying to figure this out myself for a few days now with no progress, any help would be greatly appreciated. Find attached requested files. World works perfectly on v2.4 , Update to latest, world no longer shows in single player menu. level.dat is unchanged as far as I can see. Downgrading back to 2.4 and world returns.
[NotEnough Git.zip](https://github.com/fewizz/NotEnoughIDs/files/842197/NotEnough.Git.zip)

**Comment by sfPlayer1** [comment]
I just tried it once myself without issues, so it's at least not trivially reproducible.

The log file doesn't show anything of interest, I'll need a full copy of a world save that still works when loaded in 2.4, but isn't being shown in 2.5.

**Comment by PotDucky** [comment]
Yeah I've made a new world transferred over and it works fine, Only appears to be an issue on some worlds. I'm not entirely sure if this link works for you, let me know if it doesn't. https://app.sendit.gl/sendit/YeaQ-433rPyIO-rBV5oaqp/r-cG90ZHVja3klNDBhbGx0aGVwYWNrcy5jb20=

**Comment by sfPlayer1** [comment]
I can reproduce it with the save.

**Comment by PotDucky** [comment]
Yeah same, If it definetely appears to be a level.dat issue. If I make a new world and copy the level.dat over from that, the old world shows up. However I assume there's ID issues as when loading in it crashes.

**Comment by PotDucky** [comment]
Okay so copying just the modlist from a 2.51b world, into the level.dat of the broken 2.4 world, makes the world show and doesn't have any ID mismatches.

Do you have any idea what could be causing that?

**Comment by sfPlayer1** [comment]
```
java.lang.IllegalArgumentException: Invalid dimension id -31
	at net.minecraft.world.DimensionType.func_186069_a(DimensionType.java:77) ~[atm.class:?]
	at net.minecraft.world.storage.WorldInfo.<init>(WorldInfo.java:256) ~[baa.class:?]
	at net.minecraft.world.storage.SaveFormatOld.func_186353_a(SaveFormatOld.java:102) [azz.class:?]
	at net.minecraft.world.storage.SaveFormatOld.func_75803_c(SaveFormatOld.java:91) [azz.class:?]
	at net.minecraft.world.chunk.storage.AnvilSaveConverter.func_75799_b(SourceFile:57) [azw.class:?]
	at net.minecraft.client.gui.GuiListWorldSelection.func_186795_e(SourceFile:35) [big.class:?]
	at net.minecraft.client.gui.GuiListWorldSelection.<init>(SourceFile:28) [big.class:?]
	at net.minecraft.client.gui.GuiWorldSelection.func_73866_w_(SourceFile:43) [bie.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:495) [bft.class:?]
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:965) [bcx.class:?]
	at lumien.custommainmenu.lib.actions.ActionOpenGUI.perform(ActionOpenGUI.java:110) [ActionOpenGUI.class:?]
	at lumien.custommainmenu.gui.GuiCustom.func_146284_a(GuiCustom.java:707) [GuiCustom.class:?]
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:460) [bft.class:?]
	at lumien.custommainmenu.gui.GuiCustom.func_73864_a(GuiCustom.java:245) [GuiCustom.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:548) [bft.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:517) [bft.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1700) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

Something registered a dimension type with id -31 before, but doesn't do so in the new version anymore. Note that this is not the usual dimension id, but the dimension type id.

**Comment by sfPlayer1** [comment]
name = "Limbo"
suffix = "_correlateddungeon"
id = -31
provider = instance of java.lang.Class(reflected class=io.github.elytra.correlated.world.LimboProvider, id=16282)
keepLoaded = false

**Comment by PotDucky** [comment]
Correlated Potentialistics most likely then. Thank you so much for your help!

**Comment by sfPlayer1** [comment]
This is not a NEIDs issue, Forge needs to fix their dimension type handling to tolerate mod removal/changes. In the meanwhile a tool like NBTExplorer can be used to remove the offending dimension type. It's located at "level.dat" - "Data" - "DimensionData" - "-31"
