### ISSUE TITLE
ArrayIndexOutOfBoundsException in Chunk network code

### ISSUE THREAD

**Issue by e3r** [fewizz/NotEnoughIDs#7]
Getting an exception while exploring the world.
Once it is encountered, it will happen every time that world is started/joined
(This is single player)

java.lang.ArrayIndexOutOfBoundsException
	at net.minecraft.network.play.server.S21PacketChunkData.func_149269_a(S21PacketChunkData.java:223)
	at net.minecraft.network.play.server.S26PacketMapChunkBulk.<init>(S26PacketMapChunkBulk.java:48)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:270)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at fastcraft.r.a(F:21)
	at fastcraft.Hooks.aq(F:155)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

(I have also seen it referencing the native ArrayCopy-method in S21PackedChunkData when crashing)

full log (expires 1 month from now):
http://pastebin.com/QfxfVcgd

This only happens when NotEnoughIds is present.

**Comment by fewizz** [comment]
you have this issue without fastcraft?

**Comment by e3r** [comment]
Ah, i forgot to mention that:

Samme issue without fastcraft - identical stacktrace, just without the fastcraft hooks.

**Comment by Solarstrike** [comment]
I'm having the same issue.

**Comment by fewizz** [comment]
e3r, pls, give me your "mods' folder in archive.

**Comment by Solarstrike** [comment]
Working on the bug?

**Comment by e3r** [comment]
Mods and Config:
http://1drv.ms/1NjUUYD

Config is mostly fixing of ID conflicts

You might need to do some world exploring to trigger the bug. AutoRun is included to help with that. I think X is the default binding.


One thing i noticed is that the more mods i add, the faster the bug triggers/less exploring is needed. (Might be related to number of unique blocks in a chunk?)

**Comment by Solarstrike** [comment]
Superflat is experiencing the same problem @e3r .

**Comment by Solarstrike** [comment]
@fewizz Are you working on it?

**Comment by fewizz** [comment]
Yes.

**Comment by fewizz** [comment]
e3r, give me please one of your corrupted world.

**Comment by Solarstrike** [comment]
Why are you asking for files?

**Comment by fewizz** [comment]
bcs minecraft not crashing in my comp. =P

**Comment by e3r** [comment]
Try this one. It crashes at spawn for me.

http://1drv.ms/1UPfqTl

If it doesn't crash for you I'll try to make another one.

**Comment by fewizz** [comment]
Fixed? pls test. https://drive.google.com/file/d/0B0GYhmakgvItNUs5NkNxd3pRS3c/view?usp=sharing

**Comment by Solarstrike** [comment]
The other file?

**Comment by fewizz** [comment]
updated file.

**Comment by e3r** [comment]
It seems to be fixed!  \o/

I explored quite a bit of the world in my 320+ mods pack without it crashing. Before it usually crashed after moving 10 chunks in any direction.

I'll probably get to test it more tomorrow when i try to sort out oregen, but so far so good - i'd say the issue can be closed.

Good work and awesome mod.

**Comment by Solarstrike** [comment]
Working for me too.

**Comment by Adaptivity** [comment]
New release will be later today. @fewizz also uploaded mod to curse, it's now being reviewed by mods.

**Comment by Adaptivity** [comment]
New version with fix is live.
