### ISSUE TITLE
Error with many mods, id 256.

### ISSUE THREAD

**Issue by mrvlad2** [fewizz/NotEnoughIDs#86]
A lot of popular mods gets error when i install NEID.

`java.lang.RuntimeException: Invalid id 256 - maximum id range exceeded.
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
	at twilightforest.biomes.RegistryBiomeEvent$BiomeRegistry.register(RegistryBiomeEvent.java:249)
	at twilightforest.biomes.RegistryBiomeEvent.onRegisterBiomes(RegistryBiomeEvent.java:20)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_165_RegistryBiomeEvent_onRegisterBiomes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:814)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

But I need this mod (NEID) to use another mods :/ What i need to do?

**Comment by fewizz** [comment]
I hope [that](https://github.com/fewizz/NotEnoughIDs/issues/75) will help you
