### ISSUE TITLE
Run into "Invalid id 256 - maximum id range exceeded."

### ISSUE THREAD

**Issue by Hero62** [fewizz/NotEnoughIDs#95]
Hi,

I'm loading 236 mods, and run into this issue:

`Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Extra Utilities 2 (extrautils2)
Caused by: java.lang.RuntimeException: Invalid id 256 - maximum id range exceeded.
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
	at com.rwtema.extrautils2.compatibility.CompatHelper112.register(CompatHelper112.java:52)
	at com.rwtema.extrautils2.potion.PotionsHelper.registerPotion(PotionsHelper.java:83)
	at com.rwtema.extrautils2.backend.entries.PotionEntry.postInit(PotionEntry.java:24)`

I've attached the full crashlog
[crash-2020-04-01_21.34.16-client.txt](https://github.com/fewizz/NotEnoughIDs/files/4418907/crash-2020-04-01_21.34.16-client.txt)

**Comment by fewizz** [comment]
[JEID](https://minecraft.curseforge.com/projects/jeid) should help with potions.
